version: '3.7'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:8071:8080"
    restart: 'always'
    volumes:
      - ./searxng:/etc/searxng:rw
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
    - SEARXNG_BASE_URL=https://search.whateveritworks.org
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/info/en/about"]
      interval: 2m
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: "redis:alpine"
    user: nobody
    restart: always
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m
      timeout: 5s
networks:
  searxng:
    ipam:
      driver: default
