version: '3.9'

services:
  searxng:
    container_name: searxng
    hostname: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:8071:8080"
    restart: 'always'
    volumes:
      - ./searxng:/etc/searxng:rw
      - type: bind
        source: ./favicon.png
        target: /usr/local/searxng/searx/static/themes/simple/img/searxng.png
        type: bind
        source: ./base.html
        target: /usr/local/searxng/searx/templates/simple/base.html 
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
    - SEARXNG_BASE_URL=https://search.whateveritworks.org
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng-redis:
    container_name: searxng-redis
    hostname: searxng-redis
    image: redis:latest
    user: nobody
    restart: always
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  searxng:
    ipam:
      driver: default
