# see https://docs.searxng.org/admin/settings/settings.html#use-default-settings
use_default_settings: true
formats:
  - html
server:
  secret_key: "changethis"
  limiter: true
  link_token: true
  image_proxy: true
  http_protocol_version: "1.1"
ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: dark
  infinite_scroll: false
  results_on_new_tab: true
  cache_url: https://archive.ph
outgoing:
  request_timeout: 2.0
  max_request_timeout: 10.0 
  useragent_suffix: "support@whateveritworks.org"
  pool_connections: 100
  pool_maxsize: 10 
  enable_http2: true
search:
  autocomplete: "google"
general:
  instance_name:  "whatever"
  privacypolicy_url: https://
  donation_url: https://
  contact_url: mailto:
enabled_plugins:
- 'Tor check plugin'
- 'Open Access DOI rewrite'
- 'Hostname replace'
- 'Self Information'
- 'Tracker URL remover'
- 'Hash plugin'
- 'Search on category select'
hostname_replace:
   '(.*\.)?youtube\.com$': 'yt.whateveritworks.org'
   '(.*\.)?youtu\.be$': 'yt.whateveritworks.org'
   '(.*\.)?youtube-noocookie\.com$': 'yt.whateveritworks.org'
   '(.*\.)?reddit\.com$': 'discuss-whateveritworks.org'
   '(.*\.)?redd\.it$': 'discuss-whateveritworks.org'
   '(www\.)?twitter\.com$': 'tweet.whateveritworks.org'
   'spam\.example\.com': false
redis:
  url: redis://searxng-redis:6379/0
