# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  secret_key: "changethis"
  limiter: true
  image_proxy: true
ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: dark
  infinite_scroll: true
search:
  autocomplete: "google"
general:
  instance_name:  "whatever"
  privacypolicy_url: https://
  donation_url: https://
  contact_url: mailto:
redis:
  url: redis://redis:6379/0
